const types = {
  TOGGLE_LOADING: 'TOGGLE_LOADING',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_SIDEBAR_SHOW: 'TOGGLE_SIDEBAR_SHOW',
  TOGGLE_DEVICE: "TOGGLE_DEVICE",
  EXPAND_MENU: 'EXPAND_MENU',
  SWITCH_EFFECT: 'SWITCH_EFFECT',
  LOAD_MENU: 'LOAD_MENU',
  LOAD_CURRENT_MENU: 'LOAD_CURRENT_MENU',
  SET_USER_INFO: 'SET_USER_INFO',
  SET_COLLAPSE: 'SET_COLLAPSE',
  SET_INDEX: 'SET_INDEX',
  SET_LOG: 'SET_LOG',
  SET_SENDERID: 'SET_SENDERID',
  SET_WEBSOCKET: 'SET_WEBSOCKET',
  SET_CHANGE: 'SET_CHANGE',
  SET_USER: 'SET_USER',
  SET_MSG_LIST: 'SET_MSG_LIST',
  SET_SYS_LIST: 'SET_SYS_LIST',
}

export default types
